### ISSUE TITLE
no call event OnClose (unplay editor) or OnApplicationQuit

### ISSUE THREAD

**Issue by Avatarchik** [negitoromaki/polybius#1]

**Comment by csculley** [comment]
Could you provide any more information about this issue? I'm not exactly sure what this is referring to.
This is a school project that relies on external APIs, which means its not being maintained or updated, and most likely doesn't work since the external APIs have most likely changed or restricted access. If you're wondering about something in the code, we might be able to explain our reasoning, but otherwise this project is pretty much dormant. Thanks!
